// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package users

import (
	"gorm.io/gorm"
)

// Injectors from user.provider.go:

func Wire(db *gorm.DB) *UserHandlers {
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository)
	userHandlers := ProvideUserHandlers(userService)
	return userHandlers
}
